/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BlackCube (https://sketchfab.com/blackcube4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubix-rubiks-magic-cube-animated-rigged-e26af7d1148f4e0ebcfce540d796e588
Title: Rubix / Rubiks / Magic Cube Animated Rigged
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import rubikScene from '../assets/3d/rubik.glb';

const Rubik = ({ currentAnimation, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(rubikScene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());
    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group name='Rubixcubefbx' rotation={[Math.PI / 2, 0, 0]}>
            <group name='Object_2'>
              <group name='RootNode'>
                <group
                  name='Armature'
                  position={[0.285, 0.285, -0.285]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.38}
                >
                  <group name='Object_5'>
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name='Object_35'
                      geometry={nodes.Object_35.geometry}
                      material={materials.Blau}
                      skeleton={nodes.Object_35.skeleton}
                    />
                    <skinnedMesh
                      name='Object_36'
                      geometry={nodes.Object_36.geometry}
                      material={materials.material}
                      skeleton={nodes.Object_36.skeleton}
                    />
                    <skinnedMesh
                      name='Object_37'
                      geometry={nodes.Object_37.geometry}
                      material={materials.Gelb}
                      skeleton={nodes.Object_37.skeleton}
                    />
                    <skinnedMesh
                      name='Object_38'
                      geometry={nodes.Object_38.geometry}
                      material={materials.material_3}
                      skeleton={nodes.Object_38.skeleton}
                    />
                    <skinnedMesh
                      name='Object_39'
                      geometry={nodes.Object_39.geometry}
                      material={materials.Orange}
                      skeleton={nodes.Object_39.skeleton}
                    />
                    <skinnedMesh
                      name='Object_40'
                      geometry={nodes.Object_40.geometry}
                      material={materials.material_5}
                      skeleton={nodes.Object_40.skeleton}
                    />
                    <skinnedMesh
                      name='Object_41'
                      geometry={nodes.Object_41.geometry}
                      material={materials.Inside}
                      skeleton={nodes.Object_41.skeleton}
                    />
                    <group
                      name='Object_34'
                      position={[0.285, 0.285, -0.285]}
                      scale={0.029}
                    />
                  </group>
                </group>
                <group
                  name='Rubix_Cube'
                  position={[0.285, 0.285, -0.285]}
                  scale={0.029}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Rubik;
